// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/base-app-config.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/base-app-config.json">> = Specific
  const handler = {} as typeof import("../../../app/api/base-app-config.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/farcaster.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/farcaster.json">> = Specific
  const handler = {} as typeof import("../../../app/api/farcaster.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/farcaster/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/farcaster/alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/farcaster/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/farcaster/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/farcaster/notify">> = Specific
  const handler = {} as typeof import("../../../app/api/farcaster/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/farcaster/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/farcaster/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/farcaster/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/frame/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/frame">> = Specific
  const handler = {} as typeof import("../../../app/api/frame/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/icon/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/icon">> = Specific
  const handler = {} as typeof import("../../../app/api/icon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/manifest.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/manifest.json">> = Specific
  const handler = {} as typeof import("../../../app/api/manifest.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/markets/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/markets/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/markets/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/markets">> = Specific
  const handler = {} as typeof import("../../../app/api/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/og">> = Specific
  const handler = {} as typeof import("../../../app/api/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/onchain-app-config.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onchain-app-config.json">> = Specific
  const handler = {} as typeof import("../../../app/api/onchain-app-config.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/points/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/points">> = Specific
  const handler = {} as typeof import("../../../app/api/points/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tx">> = Specific
  const handler = {} as typeof import("../../../app/api/tx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
