var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d5f8c662._.js")
R.c("server/chunks/ssr/28ea8_next_dist_c600305c._.js")
R.c("server/chunks/ssr/_gemini_antigravity_scratch_folymarket_41e70f1e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__aa8a79c4._.js")
R.c("server/chunks/ssr/28ea8_next_dist_d774651f._.js")
R.c("server/chunks/ssr/28ea8_next_dist_ca9ecffa._.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_builtin_global-error_f1c6457c.js")
R.c("server/chunks/ssr/_gemini_antigravity_scratch_folymarket_3f3f3bb1._.js")
R.c("server/chunks/ssr/_gemini_antigravity_scratch_folymarket_app_error_tsx_b94542aa._.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_b1f9d916._.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_builtin_forbidden_1f0547e6.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_builtin_unauthorized_55c7861d.js")
R.c("server/chunks/ssr/2af11_antigravity_scratch_folymarket__next-internal_server_app_page_actions_9a68a88f.js")
R.m(781612)
module.exports=R.m(781612).exports
