// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimplePredictionMarket$Type } from "./SimplePredictionMarket";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimplePredictionMarket"]: SimplePredictionMarket$Type;
    ["contracts/SimplePredictionMarket.sol:SimplePredictionMarket"]: SimplePredictionMarket$Type;
  }

  interface ContractTypesMap {
    ["SimplePredictionMarket"]: GetContractReturnType<SimplePredictionMarket$Type["abi"]>;
    ["contracts/SimplePredictionMarket.sol:SimplePredictionMarket"]: GetContractReturnType<SimplePredictionMarket$Type["abi"]>;
  }
}
