// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Simple$Type } from "./Simple";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Simple"]: Simple$Type;
    ["contracts/Simple.sol:Simple"]: Simple$Type;
  }

  interface ContractTypesMap {
    ["Simple"]: GetContractReturnType<Simple$Type["abi"]>;
    ["contracts/Simple.sol:Simple"]: GetContractReturnType<Simple$Type["abi"]>;
  }
}
