// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Simple$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Simple",
  "sourceName": "contracts/Simple.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "x",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b50607b60008190555060b3806100276000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80630c55699c14602d575b600080fd5b60336047565b604051603e91906064565b60405180910390f35b60005481565b6000819050919050565b605e81604d565b82525050565b6000602082019050607760008301846057565b9291505056fea2646970667358221220abdcd88031ab37c81519f7b0d0572bbd826fc00e956aa625a0995400ed0ca89b64736f6c63430008140033",
  "deployedBytecode": "0x6080604052348015600f57600080fd5b506004361060285760003560e01c80630c55699c14602d575b600080fd5b60336047565b604051603e91906064565b60405180910390f35b60005481565b6000819050919050565b605e81604d565b82525050565b6000602082019050607760008301846057565b9291505056fea2646970667358221220abdcd88031ab37c81519f7b0d0572bbd826fc00e956aa625a0995400ed0ca89b64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Simple",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Simple$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Simple.sol:Simple",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Simple$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Simple",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Simple$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Simple.sol:Simple",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Simple$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Simple",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Simple$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Simple.sol:Simple",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Simple$Type["abi"]>>;
}
