var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__db0584ff._.js")
R.c("server/chunks/ssr/28ea8_next_dist_c600305c._.js")
R.c("server/chunks/ssr/28ea8_next_dist_esm_build_templates_app-page_4421e6f7.js")
R.c("server/chunks/ssr/[root-of-the-server]__18989e51._.js")
R.c("server/chunks/ssr/28ea8_next_dist_d774651f._.js")
R.c("server/chunks/ssr/28ea8_next_dist_ca9ecffa._.js")
R.c("server/chunks/ssr/_gemini_antigravity_scratch_folymarket_3f3f3bb1._.js")
R.c("server/chunks/ssr/_gemini_antigravity_scratch_folymarket_app_error_tsx_b94542aa._.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_b1f9d916._.js")
R.c("server/chunks/ssr/28ea8_next_dist_client_components_builtin_forbidden_1f0547e6.js")
R.c("server/chunks/ssr/2078d_scratch_folymarket__next-internal_server_app__not-found_page_actions_89b59609.js")
R.m(362348)
module.exports=R.m(362348).exports
