// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PredictionMarket$Type } from "./PredictionMarket";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PredictionMarket"]: PredictionMarket$Type;
    ["contracts/PredictionMarket.sol:PredictionMarket"]: PredictionMarket$Type;
  }

  interface ContractTypesMap {
    ["PredictionMarket"]: GetContractReturnType<PredictionMarket$Type["abi"]>;
    ["contracts/PredictionMarket.sol:PredictionMarket"]: GetContractReturnType<PredictionMarket$Type["abi"]>;
  }
}
